# Generated by Django 5.1.4 on 2024-12-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('player_count', models.IntegerField()),
                ('results', models.IntegerField()),
            ],
        ),
    ]
