# Generated by Django 5.1.4 on 2024-12-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0002_playerpop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('player_count', models.IntegerField()),
                ('results', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
